<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transformations"
    nsURI="platform:/resource/uml2cs-transformations/configuration/Transformations.ecore"
    nsPrefix="transformations">
  <eAnnotations source="CDDToolkit">
    <details key="Ontology" value="Transformations.owl"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationConfig">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Root node for a transformation configuration model"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="#//Mapping" containment="true" eOpposite="#//Mapping/config">
      <eAnnotations source="GenModel">
        <details key="documentation" value="Programming language mapping to use"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true">
      <eAnnotations source="GenModel">
        <details key="documentation" value="Path to store the generated build files"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="GenModel">
        <details key="documentation" value="Path to write the generated code to"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saveModels" lowerBound="1"
        eType="#//SaveModelType">
      <eAnnotations source="GenModel">
        <details key="documentation" value="Select whether to save all intermediate models, save only the last model or don't save models"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observer" lowerBound="1"
        eType="#//UML2Observer" containment="true" eOpposite="#//UML2Observer/config">
      <eAnnotations source="GenModel">
        <details key="documentation" value="Variant of UML2Observer transformation to use"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applet" lowerBound="1"
        eType="#//UML2Applet" containment="true" eOpposite="#//UML2Applet/config">
      <eAnnotations source="GenModel">
        <details key="documentation" value="Variant of UML2Applet transformation to use"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" abstract="true">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Programming language mapping"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//TransformationConfig" eOpposite="#//TransformationConfig/mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaMapping" eSuperTypes="#//Mapping">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Java language mapping"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/Transformations.owl#JavaMappingsPlatform"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" lowerBound="1"
        eType="#//JavaDataTypes" containment="true" eOpposite="#//JavaDataTypes/mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaDataTypes" abstract="true">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Java language data types"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="#//JavaMapping" eOpposite="#//JavaMapping/dataTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Java1DataTypes" eSuperTypes="#//JavaDataTypes">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Java 1.0 data types"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/Transformations.owl#Java1Platform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Java2DataTypes" eSuperTypes="#//JavaDataTypes">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Java 1.2 data types"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/Transformations.owl#Java2Platform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UML2Observer">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Implements the Observer profile"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//TransformationConfig" eOpposite="#//TransformationConfig/observer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UML2JavaObserver" eSuperTypes="#//UML2Observer">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Implements the Observer profile using the java.util.Observer API"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/Transformations.owl#JavaObserverPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UML2Applet">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Implements the Applet profile using a Java AWT Applet"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/Transformations.owl#AppletPlatform"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//TransformationConfig" eOpposite="#//TransformationConfig/applet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UML2MIDlet" eSuperTypes="#//UML2Applet">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Implements the Applet profile using a Java MIDP MIDlet"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/Transformations.owl#MIDletPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SaveModelType">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Save all intermediate models, only the last model or no models (generate code only)"/>
    </eAnnotations>
    <eLiterals name="none"/>
    <eLiterals name="last" value="1"/>
    <eLiterals name="all" value="2"/>
  </eClassifiers>
</ecore:EPackage>
