<?xml version="1.0" encoding="ISO-8859-1"?>
<XML:Root xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:XML="XML" startLine="1" startColumn="13" endLine="3" endColumn="14" name="parameters">
  <children xsi:type="XML:Text" startLine="2" startColumn="2" name="#text" value="&#xA;&#x9;"/>
  <children xsi:type="XML:Element" startLine="2" startColumn="66" endLine="2" endColumn="66" name="param">
    <children xsi:type="XML:Attribute" name="name" value="path"/>
    <children xsi:type="XML:Attribute" name="value" value="uml2cs-instantmessenger-default/src"/>
  </children>
  <children xsi:type="XML:Text" startLine="3" startColumn="1" name="#text" value="&#xA;"/>
</XML:Root>
