/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package be.ac.vub.uml2cs.transformations.validation;

import be.ac.vub.uml2cs.transformations.Mapping;
import be.ac.vub.uml2cs.transformations.SaveModelType;
import be.ac.vub.uml2cs.transformations.UML2Applet;
import be.ac.vub.uml2cs.transformations.UML2Observer;

/**
 * A sample validator interface for {@link be.ac.vub.uml2cs.transformations.TransformationConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformationConfigValidator {
	boolean validate();

	boolean validateBuildPath(String value);
	boolean validateTargetPath(String value);
	boolean validateMapping(Mapping value);
	boolean validateSaveModels(SaveModelType value);
	boolean validateObserver(UML2Observer value);
	boolean validateApplet(UML2Applet value);
}
