/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package be.ac.vub.uml2cs.transformations.validation;

import be.ac.vub.uml2cs.transformations.TransformationConfig;

/**
 * A sample validator interface for {@link be.ac.vub.uml2cs.transformations.UML2Observer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UML2ObserverValidator {
	boolean validate();

	boolean validateConfig(TransformationConfig value);
}
