<?xml version="1.0" encoding="UTF-8"?>
<instantmessenger:InstantMessengerConfiguration xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:instantmessenger="platform:/resource/uml2cs-instantmessenger-model/configuration/InstantMessenger.ecore"
    xmlns:transformations="platform:/resource/uml2cs-transformations/configuration/Transformations.ecore" buildPath="uml2cs-instantmessenger-java2/build"
    targetPath="uml2cs-instantmessenger-java2/src" saveModels="last" deploymentTarget="java2/applet/">
  <mapping xsi:type="transformations:JavaMapping">
    <dataTypes xsi:type="transformations:Java2DataTypes"/>
  </mapping>
  <observer xsi:type="transformations:UML2JavaObserver"/>
  <applet/>
  <localNetwork/>
  <jabberNetwork>
    <jabberTransport xsi:type="instantmessenger:DefaultJabberTransport"/>
  </jabberNetwork>
  <userInterface xsi:type="instantmessenger:AWTUserInterface"/>
  <packaging xsi:type="instantmessenger:WebAppletPackaging"/>
</instantmessenger:InstantMessengerConfiguration>
