<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml2profiles"
    nsURI="platform:/resource/uml2cs-transformations/metamodel/UML2Profiles.ecore"
    nsPrefix="uml2profiles">
  <eClassifiers xsi:type="ecore:EClass" name="Import" abstract="true" eSuperTypes="../profiles/Accessors.profile.uml#_F7CJQDgxEduNII1tDKqNvA ../profiles/Applet.profile.uml#_i8gYkDgqEduNII1tDKqNvA http://www.eclipse.org/uml2/2.0.0/UML#//Element ../profiles/Observer.profile.uml#_g6Z98TgqEduNII1tDKqNvA ../profiles/Singleton.profile.uml#_eMWcQTgqEduNII1tDKqNvA ../profiles/Final.profile.uml#_4InvETntEduHCOb_wCU8nA pathmap://UML_PROFILES/Standard.profile.uml#_yzU5-IinEdqtvbnfB2L_5w"/>
</ecore:EPackage>
