<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="instantmessenger"
    nsURI="http://ssel.vub.ac.be/uml2cs/InstantMessenger" nsPrefix="instantmessenger">
  <eAnnotations source="CDDToolkit">
    <details key="Ontology" value="InstantMessenger.owl"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="InstantMessengerConfiguration" eSuperTypes="../../../plugin/be.ac.vub.uml2cs.transformations.config/model/Transformations.ecore#//TransformationConfig">
    <eAnnotations source="GenModel">
      <details key="documentation" value="Root node for an instant messenger configuration model"/>
    </eAnnotations>
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#InstantMessengerPlatform"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deploymentTarget" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localNetwork" eType="#//LocalNetwork"
        defaultValueLiteral="" containment="true" eOpposite="#//LocalNetwork/config"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jabberNetwork" eType="#//JabberNetwork"
        containment="true" eOpposite="#//JabberNetwork/config"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInterface" lowerBound="1"
        upperBound="-1" eType="#//UserInterface" containment="true" eOpposite="#//UserInterface/config"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packaging" lowerBound="1"
        eType="#//Packaging" containment="true" eOpposite="#//Packaging/config"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalNetwork">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#LocalPlatform"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//InstantMessengerConfiguration" eOpposite="#//InstantMessengerConfiguration/localNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JabberNetwork">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#JabberPlatform"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jabberTransport" lowerBound="1"
        eType="#//JabberTransport" defaultValueLiteral="" containment="true" eOpposite="#//JabberTransport/jabberNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//InstantMessengerConfiguration" eOpposite="#//InstantMessengerConfiguration/jabberNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JabberTransport" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jabberNetwork" lowerBound="1"
        eType="#//JabberNetwork" eOpposite="#//JabberNetwork/jabberTransport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultJabberTransport" eSuperTypes="#//JabberTransport">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#DefaultJabberPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEJabberTransport" eSuperTypes="#//JabberTransport">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#MEJabberPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//InstantMessengerConfiguration" eOpposite="#//InstantMessengerConfiguration/userInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AWTUserInterface" eSuperTypes="#//UserInterface">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#AWTPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwingUserInterface" eSuperTypes="#//UserInterface">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#SwingPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LCDUIUserInterface" eSuperTypes="#//UserInterface">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#LCDUIPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Packaging" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//InstantMessengerConfiguration" eOpposite="#//InstantMessengerConfiguration/packaging"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebAppletPackaging" eSuperTypes="#//Packaging">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#WebAppletPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpkgAppletPackaging" eSuperTypes="#//Packaging">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#IpkgAppletPlatform"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIDletPackaging" eSuperTypes="#//Packaging">
    <eAnnotations source="CDDToolkit">
      <details key="ContextConstraint" value="http://local/InstantMessenger.owl#MIDletPlatform"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
