/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package be.ac.vub.uml2cs.instantmessenger.validation;

import org.eclipse.emf.common.util.EList;

import be.ac.vub.uml2cs.instantmessenger.JabberNetwork;
import be.ac.vub.uml2cs.instantmessenger.LocalNetwork;
import be.ac.vub.uml2cs.instantmessenger.Packaging;
import be.ac.vub.uml2cs.instantmessenger.UserInterface;

/**
 * A sample validator interface for {@link be.ac.vub.uml2cs.instantmessenger.InstantMessengerConfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstantMessengerConfigurationValidator {
	boolean validate();

	boolean validateDeploymentTarget(String value);
	boolean validateLocalNetwork(LocalNetwork value);
	boolean validateJabberNetwork(JabberNetwork value);
	boolean validateUserInterface(EList<UserInterface> value);
	boolean validatePackaging(Packaging value);
}
